---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      react:
        patterns:
          - react
          - react-dom
      react-router:
        patterns:
          - "@react-router/*"
          - react-router
      sentry:
        patterns:
          - "@sentry/*"
        exclude-patterns:
          - "@sentry/vite-plugin"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
