services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: diswantin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
